### PR TITLE
Fixes end of day

### PR DESCRIPTION
**Pull request by Goody3099**
This is the fixed index.html and the matt.html for you all to copy or whatever...

### CODE REVIEW

**Review by corneliajohnson — APPROVED** [review]
Everythings looks from from yesterday

**Comment by ember-parr** [comment]
Doing things!

**Review by cArel116 — CHANGES_REQUESTED** [review]
Please drop <h2> tag to next line (same indentation as <ul>.

**Comment by corneliajohnson** [comment]
@ember-parr @cArel116 @Goody3099   just practice

**Review by ember-parr — APPROVED** [review]

**Review by corneliajohnson — APPROVED** [review]
Looks Good

**Review by cArel116 — CHANGES_REQUESTED** [review]
Doc the same... changes didn't take. Please re-commit.

**Pull request closed without merging**
